// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzVymHBhRuHkX5kXAywNb0ak4Zq0Ly-d4',
    appId: '1:265812417783:web:f58fbf336086c941fa07f2',
    messagingSenderId: '265812417783',
    projectId: 'todo-1728f',
    authDomain: 'todo-1728f.firebaseapp.com',
    storageBucket: 'todo-1728f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7B1isB1O9xUIlrS1P27-k4zxKGLpJmtg',
    appId: '1:265812417783:android:ff443d12329d8da8fa07f2',
    messagingSenderId: '265812417783',
    projectId: 'todo-1728f',
    storageBucket: 'todo-1728f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9mjyeCYBnMUACudjH_Fek_ahW156gmI8',
    appId: '1:265812417783:ios:5ca5029643e4aa1cfa07f2',
    messagingSenderId: '265812417783',
    projectId: 'todo-1728f',
    storageBucket: 'todo-1728f.appspot.com',
    iosClientId: '265812417783-17s4mdmo5t7h8chncqocdjnbn140uuvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9mjyeCYBnMUACudjH_Fek_ahW156gmI8',
    appId: '1:265812417783:ios:5ca5029643e4aa1cfa07f2',
    messagingSenderId: '265812417783',
    projectId: 'todo-1728f',
    storageBucket: 'todo-1728f.appspot.com',
    iosClientId: '265812417783-17s4mdmo5t7h8chncqocdjnbn140uuvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzVymHBhRuHkX5kXAywNb0ak4Zq0Ly-d4',
    appId: '1:265812417783:web:3c60b9da9b739ce5fa07f2',
    messagingSenderId: '265812417783',
    projectId: 'todo-1728f',
    authDomain: 'todo-1728f.firebaseapp.com',
    storageBucket: 'todo-1728f.appspot.com',
  );
}
